version: '3.8'
services:
  dev-db:
    image: mysql:8.0.32
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DB: ${DB_NAME}
